apiVersion: v1
kind: Pod
metadata:
  name: app-with-sync
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: main-app
    image: nginx:1.14.2
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/
    ports:
    - containerPort: 80
  - name: sidecar
    image: k8s.gcr.io/git-sync:v3.1.1
    volumeMounts:
    - name: html
      mountPath: /tmp/git
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/nigelpoulton/ps-sidecar.git
    - name: GIT_SYNC_DEST
      value: "html"
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEPTH
      value: "1"